// AUTO-GENERATED by build_data.py — 실데이터(2026-07). 값 변경은 build_data.py 또는 Sheets 에서.
window.CONTRACT_DB = {
  "packages": [
    {
      "id": "PKG-1M",
      "name": "동네확보 프로젝트",
      "durationMonths": 1,
      "listSupply": 320000,
      "discount": 70000,
      "netSupply": 250000,
      "vat": 25000,
      "contractTotal": 275000,
      "lines": [
        {
          "no": 1,
          "item": "비즈프로필 후기",
          "desc": "좋은 후기로 고객 신뢰도 상승",
          "qty": 5,
          "unit": "개",
          "months": 1,
          "unitPrice": 5000,
          "amount": 25000
        },
        {
          "no": 2,
          "item": "비즈프로필 단골",
          "desc": "실유저 단골 유입을 통한 비즈프로필 신뢰도 상승",
          "qty": 50,
          "unit": "개",
          "months": 1,
          "unitPrice": 500,
          "amount": 25000
        },
        {
          "no": 3,
          "item": "비즈프로필 찜",
          "desc": "찜(저장) 수 증대로 프로필 활성화 지수 상승 및 검색 노출 순위 개선",
          "qty": 50,
          "unit": "개",
          "months": 1,
          "unitPrice": 500,
          "amount": 25000
        },
        {
          "no": 4,
          "item": "소식글 작성",
          "desc": "홍보용 소식글 작성으로 비즈프로필 홍보",
          "qty": 3,
          "unit": "개",
          "months": 1,
          "unitPrice": 15000,
          "amount": 45000
        },
        {
          "no": 5,
          "item": "동네생활 게시글",
          "desc": "동네생활 게시판 게시글 등록으로 지역 커뮤니티 내 입소문 홍보 확산",
          "qty": 5,
          "unit": "개",
          "months": 1,
          "unitPrice": 20000,
          "amount": 100000
        },
        {
          "no": 6,
          "item": "소식글 관심",
          "desc": "홍보용 소식글 작성 후 관심으로 상위노출 확보",
          "qty": 100,
          "unit": "개",
          "months": 1,
          "unitPrice": 1000,
          "amount": 100000
        }
      ]
    },
    {
      "id": "PKG-3M",
      "name": "동네선점 프로젝트",
      "durationMonths": 3,
      "listSupply": 800000,
      "discount": 50000,
      "netSupply": 750000,
      "vat": 75000,
      "contractTotal": 825000,
      "lines": [
        {
          "no": 1,
          "item": "비즈프로필 후기",
          "desc": "좋은 후기로 고객 신뢰도 상승",
          "qty": 60,
          "unit": "개",
          "months": 3,
          "unitPrice": 6000,
          "amount": 360000
        },
        {
          "no": 2,
          "item": "비즈프로필 단골",
          "desc": "실유저 단골 유입을 통한 비즈프로필 신뢰도 상승",
          "qty": 100,
          "unit": "개",
          "months": 3,
          "unitPrice": 500,
          "amount": 50000
        },
        {
          "no": 3,
          "item": "비즈프로필 찜",
          "desc": "찜(저장) 수 증대로 프로필 활성화 지수 상승 및 검색 노출 순위 개선",
          "qty": 100,
          "unit": "개",
          "months": 3,
          "unitPrice": 500,
          "amount": 50000
        },
        {
          "no": 4,
          "item": "소식글 작성",
          "desc": "홍보용 소식글 작성으로 비즈프로필 홍보",
          "qty": 12,
          "unit": "개",
          "months": 3,
          "unitPrice": 15000,
          "amount": 180000
        },
        {
          "no": 5,
          "item": "동네생활 게시글",
          "desc": "동네생활 게시판 게시글 등록으로 지역 커뮤니티 내 입소문 홍보 확산",
          "qty": 8,
          "unit": "개",
          "months": 3,
          "unitPrice": 20000,
          "amount": 160000
        }
      ]
    },
    {
      "id": "PKG-6M",
      "name": "동네점유 프로젝트",
      "durationMonths": 6,
      "listSupply": 1950000,
      "discount": 450000,
      "netSupply": 1500000,
      "vat": 150000,
      "contractTotal": 1650000,
      "lines": [
        {
          "no": 1,
          "item": "비즈프로필 후기",
          "desc": "실제 후기 등록으로 비즈프로필 신뢰도 및 구매 전환율 상승",
          "qty": 150,
          "unit": "개",
          "months": 6,
          "unitPrice": 5000,
          "amount": 750000
        },
        {
          "no": 2,
          "item": "비즈프로필 단골",
          "desc": "실유저 단골 유입을 통한 비즈프로필 신뢰도 상승",
          "qty": 250,
          "unit": "개",
          "months": 6,
          "unitPrice": 500,
          "amount": 125000
        },
        {
          "no": 3,
          "item": "비즈프로필 찜",
          "desc": "찜(저장) 수 증대로 프로필 활성화 지수 상승 및 검색 노출 순위 개선",
          "qty": 250,
          "unit": "개",
          "months": 6,
          "unitPrice": 500,
          "amount": 125000
        },
        {
          "no": 4,
          "item": "소식글 작성",
          "desc": "홍보용 소식글 작성으로 비즈프로필 홍보",
          "qty": 30,
          "unit": "개",
          "months": 6,
          "unitPrice": 15000,
          "amount": 450000
        },
        {
          "no": 5,
          "item": "동네생활 게시글",
          "desc": "동네생활 게시판 게시글 등록으로 지역 커뮤니티 내 입소문 홍보 확산",
          "qty": 20,
          "unit": "개",
          "months": 6,
          "unitPrice": 20000,
          "amount": 400000
        },
        {
          "no": 6,
          "item": "쇼츠 제작",
          "desc": "홍보용 짧은 영상(쇼츠) 제작 및 게시로 시각적 홍보 효과 강화",
          "qty": 1,
          "unit": "개",
          "months": 6,
          "unitPrice": 100000,
          "amount": 100000
        }
      ]
    },
    {
      "id": "PKG-12M",
      "name": "동네장악 프로젝트",
      "durationMonths": 12,
      "listSupply": 4500000,
      "discount": 1500000,
      "netSupply": 3000000,
      "vat": 300000,
      "contractTotal": 3300000,
      "lines": [
        {
          "no": 1,
          "item": "비즈프로필 후기",
          "desc": "좋은 후기로 고객 신뢰도 상승",
          "qty": 450,
          "unit": "개",
          "months": 12,
          "unitPrice": 5000,
          "amount": 2250000
        },
        {
          "no": 2,
          "item": "비즈프로필 단골",
          "desc": "실유저 단골 유입을 통한 비즈프로필 신뢰도 상승",
          "qty": 600,
          "unit": "개",
          "months": 12,
          "unitPrice": 500,
          "amount": 300000
        },
        {
          "no": 3,
          "item": "비즈프로필 찜",
          "desc": "찜(저장) 수 증대로 프로필 활성화 지수 상승 및 검색 노출 순위 개선",
          "qty": 600,
          "unit": "개",
          "months": 12,
          "unitPrice": 500,
          "amount": 300000
        },
        {
          "no": 4,
          "item": "소식글 작성",
          "desc": "홍보용 소식글 작성으로 비즈프로필 홍보",
          "qty": 70,
          "unit": "개",
          "months": 12,
          "unitPrice": 5000,
          "amount": 350000
        },
        {
          "no": 5,
          "item": "동네생활 게시글",
          "desc": "동네생활 게시판 게시글 등록으로 지역 커뮤니티 내 입소문 홍보 확산",
          "qty": 45,
          "unit": "개",
          "months": 12,
          "unitPrice": 20000,
          "amount": 900000
        },
        {
          "no": 6,
          "item": "쇼츠 제작",
          "desc": "홍보용 짧은 영상(쇼츠) 제작 및 게시로 시각적 홍보 효과 강화",
          "qty": 4,
          "unit": "개",
          "months": 12,
          "unitPrice": 100000,
          "amount": 400000
        }
      ]
    }
  ],
  "reps": [
    {
      "id": "REP-01",
      "name": "김호재",
      "phone": "010-2439-6233"
    },
    {
      "id": "REP-02",
      "name": "이화인",
      "phone": "010-2321-3431"
    },
    {
      "id": "REP-03",
      "name": "한영숙",
      "phone": "010-2588-2101"
    },
    {
      "id": "REP-04",
      "name": "김철현",
      "phone": "010-9135-0979"
    },
    {
      "id": "REP-05",
      "name": "김사랑",
      "phone": "010-3496-7834"
    },
    {
      "id": "REP-06",
      "name": "장민환",
      "phone": "010-5429-5016"
    },
    {
      "id": "REP-07",
      "name": "최원태",
      "phone": "010-7374-4423"
    },
    {
      "id": "REP-08",
      "name": "강종섭",
      "phone": "010-7928-1110"
    },
    {
      "id": "REP-09",
      "name": "박성준",
      "phone": "010-5733-3773"
    },
    {
      "id": "REP-10",
      "name": "김수인",
      "phone": "010-5670-0588"
    },
    {
      "id": "REP-11",
      "name": "이병우",
      "phone": "010-5729-8201"
    },
    {
      "id": "REP-12",
      "name": "김대환",
      "phone": "010-5747-8499"
    },
    {
      "id": "REP-13",
      "name": "이푸름",
      "phone": "010-6722-2694"
    }
  ],
  "customers": [
    {
      "id": "CUS-0001",
      "company": "(예시)행복한치과의원",
      "ceo": "김철수",
      "bizNo": "111-22-33333",
      "address": "서울시 강남구 테헤란로 1",
      "phone": "010-9000-0001",
      "email": "happy@dental.kr"
    },
    {
      "id": "CUS-0002",
      "company": "(예시)우리동네카페",
      "ceo": "이영희",
      "bizNo": "444-55-66666",
      "address": "경기도 고양시 덕양구 2",
      "phone": "010-9000-0002",
      "email": "cafe@town.kr"
    }
  ]
};
