// AUTO-GENERATED by build_data.py — example data, replace with real values.
window.CONTRACT_DB = {
  "items": [
    {
      "key": "review",
      "item": "비즈프로필 후기",
      "unit": "건",
      "unitPrice": 15000,
      "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
    },
    {
      "key": "regular",
      "item": "비즈프로필 단골",
      "unit": "명",
      "unitPrice": 3000,
      "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
    },
    {
      "key": "like",
      "item": "비즈프로필 찜",
      "unit": "건",
      "unitPrice": 3000,
      "desc": "저장(찜)으로 프로필 활성화 및 검색시 상단 노출"
    },
    {
      "key": "post",
      "item": "소식글 작성",
      "unit": "건",
      "unitPrice": 30000,
      "desc": "업체 홍보 소식글 작성으로 비즈프로필 유입"
    },
    {
      "key": "postlike",
      "item": "소식글 찜",
      "unit": "건",
      "unitPrice": 2000,
      "desc": "소식글 저장(찜)으로 노출 기간 연장 및 재방문 유도"
    },
    {
      "key": "town",
      "item": "동네생활 게시글",
      "unit": "건",
      "unitPrice": 50000,
      "desc": "당근 동네생활 채널 운영정책을 준수한 게시글 기획·작성"
    },
    {
      "key": "shortform",
      "item": "쇼폼 영상 제작",
      "unit": "편",
      "unitPrice": 150000,
      "desc": "업체 홍보 쇼폼 영상 기획·촬영·편집"
    },
    {
      "key": "ops",
      "item": "운영·리포트",
      "unit": "월",
      "unitPrice": 100000,
      "desc": "전담 관리팀 배치, 상담 지원, 보고 리포트 발행"
    }
  ],
  "packages": [
    {
      "id": "PKG-STD",
      "name": "스탠다드",
      "durationMonths": 3,
      "listSupply": 1260000,
      "discount": 126000,
      "netSupply": 1134000,
      "vat": 113000,
      "contractTotal": 1247000,
      "lines": [
        {
          "key": "review",
          "item": "비즈프로필 후기",
          "unit": "건",
          "qty": 20,
          "unitPrice": 15000,
          "amount": 300000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "regular",
          "item": "비즈프로필 단골",
          "unit": "명",
          "qty": 50,
          "unitPrice": 3000,
          "amount": 150000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "like",
          "item": "비즈프로필 찜",
          "unit": "건",
          "qty": 30,
          "unitPrice": 3000,
          "amount": 90000,
          "desc": "저장(찜)으로 프로필 활성화 및 검색시 상단 노출"
        },
        {
          "key": "post",
          "item": "소식글 작성",
          "unit": "건",
          "qty": 8,
          "unitPrice": 30000,
          "amount": 240000,
          "desc": "업체 홍보 소식글 작성으로 비즈프로필 유입"
        },
        {
          "key": "postlike",
          "item": "소식글 찜",
          "unit": "건",
          "qty": 40,
          "unitPrice": 2000,
          "amount": 80000,
          "desc": "소식글 저장(찜)으로 노출 기간 연장 및 재방문 유도"
        },
        {
          "key": "town",
          "item": "동네생활 게시글",
          "unit": "건",
          "qty": 2,
          "unitPrice": 50000,
          "amount": 100000,
          "desc": "당근 동네생활 채널 운영정책을 준수한 게시글 기획·작성"
        },
        {
          "key": "shortform",
          "item": "쇼폼 영상 제작",
          "unit": "편",
          "qty": 0,
          "unitPrice": 150000,
          "amount": 0,
          "desc": "업체 홍보 쇼폼 영상 기획·촬영·편집"
        },
        {
          "key": "ops",
          "item": "운영·리포트",
          "unit": "월",
          "qty": 3,
          "unitPrice": 100000,
          "amount": 300000,
          "desc": "전담 관리팀 배치, 상담 지원, 보고 리포트 발행"
        }
      ]
    },
    {
      "id": "PKG-DLX",
      "name": "디럭스",
      "durationMonths": 6,
      "listSupply": 2670000,
      "discount": 320000,
      "netSupply": 2350000,
      "vat": 235000,
      "contractTotal": 2585000,
      "lines": [
        {
          "key": "review",
          "item": "비즈프로필 후기",
          "unit": "건",
          "qty": 40,
          "unitPrice": 15000,
          "amount": 600000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "regular",
          "item": "비즈프로필 단골",
          "unit": "명",
          "qty": 100,
          "unitPrice": 3000,
          "amount": 300000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "like",
          "item": "비즈프로필 찜",
          "unit": "건",
          "qty": 60,
          "unitPrice": 3000,
          "amount": 180000,
          "desc": "저장(찜)으로 프로필 활성화 및 검색시 상단 노출"
        },
        {
          "key": "post",
          "item": "소식글 작성",
          "unit": "건",
          "qty": 16,
          "unitPrice": 30000,
          "amount": 480000,
          "desc": "업체 홍보 소식글 작성으로 비즈프로필 유입"
        },
        {
          "key": "postlike",
          "item": "소식글 찜",
          "unit": "건",
          "qty": 80,
          "unitPrice": 2000,
          "amount": 160000,
          "desc": "소식글 저장(찜)으로 노출 기간 연장 및 재방문 유도"
        },
        {
          "key": "town",
          "item": "동네생활 게시글",
          "unit": "건",
          "qty": 4,
          "unitPrice": 50000,
          "amount": 200000,
          "desc": "당근 동네생활 채널 운영정책을 준수한 게시글 기획·작성"
        },
        {
          "key": "shortform",
          "item": "쇼폼 영상 제작",
          "unit": "편",
          "qty": 1,
          "unitPrice": 150000,
          "amount": 150000,
          "desc": "업체 홍보 쇼폼 영상 기획·촬영·편집"
        },
        {
          "key": "ops",
          "item": "운영·리포트",
          "unit": "월",
          "qty": 6,
          "unitPrice": 100000,
          "amount": 600000,
          "desc": "전담 관리팀 배치, 상담 지원, 보고 리포트 발행"
        }
      ]
    },
    {
      "id": "PKG-PRM",
      "name": "프리미엄",
      "durationMonths": 6,
      "listSupply": 3910000,
      "discount": 586000,
      "netSupply": 3324000,
      "vat": 332000,
      "contractTotal": 3656000,
      "lines": [
        {
          "key": "review",
          "item": "비즈프로필 후기",
          "unit": "건",
          "qty": 60,
          "unitPrice": 15000,
          "amount": 900000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "regular",
          "item": "비즈프로필 단골",
          "unit": "명",
          "qty": 150,
          "unitPrice": 3000,
          "amount": 450000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "like",
          "item": "비즈프로필 찜",
          "unit": "건",
          "qty": 100,
          "unitPrice": 3000,
          "amount": 300000,
          "desc": "저장(찜)으로 프로필 활성화 및 검색시 상단 노출"
        },
        {
          "key": "post",
          "item": "소식글 작성",
          "unit": "건",
          "qty": 24,
          "unitPrice": 30000,
          "amount": 720000,
          "desc": "업체 홍보 소식글 작성으로 비즈프로필 유입"
        },
        {
          "key": "postlike",
          "item": "소식글 찜",
          "unit": "건",
          "qty": 120,
          "unitPrice": 2000,
          "amount": 240000,
          "desc": "소식글 저장(찜)으로 노출 기간 연장 및 재방문 유도"
        },
        {
          "key": "town",
          "item": "동네생활 게시글",
          "unit": "건",
          "qty": 8,
          "unitPrice": 50000,
          "amount": 400000,
          "desc": "당근 동네생활 채널 운영정책을 준수한 게시글 기획·작성"
        },
        {
          "key": "shortform",
          "item": "쇼폼 영상 제작",
          "unit": "편",
          "qty": 2,
          "unitPrice": 150000,
          "amount": 300000,
          "desc": "업체 홍보 쇼폼 영상 기획·촬영·편집"
        },
        {
          "key": "ops",
          "item": "운영·리포트",
          "unit": "월",
          "qty": 6,
          "unitPrice": 100000,
          "amount": 600000,
          "desc": "전담 관리팀 배치, 상담 지원, 보고 리포트 발행"
        }
      ]
    },
    {
      "id": "PKG-ENT",
      "name": "엔터프라이즈",
      "durationMonths": 12,
      "listSupply": 7520000,
      "discount": 1354000,
      "netSupply": 6166000,
      "vat": 617000,
      "contractTotal": 6783000,
      "lines": [
        {
          "key": "review",
          "item": "비즈프로필 후기",
          "unit": "건",
          "qty": 100,
          "unitPrice": 15000,
          "amount": 1500000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "regular",
          "item": "비즈프로필 단골",
          "unit": "명",
          "qty": 300,
          "unitPrice": 3000,
          "amount": 900000,
          "desc": "좋은 후기와 단골 숫자로 고객 신뢰도 상승"
        },
        {
          "key": "like",
          "item": "비즈프로필 찜",
          "unit": "건",
          "qty": 200,
          "unitPrice": 3000,
          "amount": 600000,
          "desc": "저장(찜)으로 프로필 활성화 및 검색시 상단 노출"
        },
        {
          "key": "post",
          "item": "소식글 작성",
          "unit": "건",
          "qty": 48,
          "unitPrice": 30000,
          "amount": 1440000,
          "desc": "업체 홍보 소식글 작성으로 비즈프로필 유입"
        },
        {
          "key": "postlike",
          "item": "소식글 찜",
          "unit": "건",
          "qty": 240,
          "unitPrice": 2000,
          "amount": 480000,
          "desc": "소식글 저장(찜)으로 노출 기간 연장 및 재방문 유도"
        },
        {
          "key": "town",
          "item": "동네생활 게시글",
          "unit": "건",
          "qty": 16,
          "unitPrice": 50000,
          "amount": 800000,
          "desc": "당근 동네생활 채널 운영정책을 준수한 게시글 기획·작성"
        },
        {
          "key": "shortform",
          "item": "쇼폼 영상 제작",
          "unit": "편",
          "qty": 4,
          "unitPrice": 150000,
          "amount": 600000,
          "desc": "업체 홍보 쇼폼 영상 기획·촬영·편집"
        },
        {
          "key": "ops",
          "item": "운영·리포트",
          "unit": "월",
          "qty": 12,
          "unitPrice": 100000,
          "amount": 1200000,
          "desc": "전담 관리팀 배치, 상담 지원, 보고 리포트 발행"
        }
      ]
    }
  ],
  "reps": [
    {
      "id": "REP-01",
      "name": "김수인",
      "phone": "010-1234-4567",
      "email": "sikim@connectwise.co.kr",
      "dept": "영업팀"
    },
    {
      "id": "REP-02",
      "name": "이민호",
      "phone": "010-2222-3456",
      "email": "mhlee@connectwise.co.kr",
      "dept": "영업팀"
    },
    {
      "id": "REP-03",
      "name": "박지훈",
      "phone": "010-3333-7890",
      "email": "jhpark@connectwise.co.kr",
      "dept": "영업2팀"
    },
    {
      "id": "REP-04",
      "name": "정하나",
      "phone": "010-4444-1212",
      "email": "hjung@connectwise.co.kr",
      "dept": "영업2팀"
    }
  ],
  "customers": [
    {
      "id": "CUS-0001",
      "company": "행복한치과의원",
      "ceo": "김철수",
      "bizNo": "111-22-33333",
      "address": "서울시 강남구 테헤란로 1",
      "phone": "010-9000-0001",
      "email": "happy@dental.kr"
    },
    {
      "id": "CUS-0002",
      "company": "우리동네카페",
      "ceo": "이영희",
      "bizNo": "444-55-66666",
      "address": "경기도 고양시 덕양구 2",
      "phone": "010-9000-0002",
      "email": "cafe@town.kr"
    }
  ]
};
